# Generated by Django 2.1.7 on 2021-03-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend_Request',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
