# Generated by Django 2.1.7 on 2021-03-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210301_0105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show_Teachers',
        ),
    ]
