# Generated by Django 2.1.7 on 2021-03-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_show_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Profile',
            new_name='user',
        ),
    ]
