# Generated by Django 2.1.7 on 2021-03-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_reporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporter',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='przedmiot',
            field=models.TextField(default=' '),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
