# Generated by Django 2.1.7 on 2021-03-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210305_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opis',
            field=models.TextField(default='empty', max_length='30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='przedmiot',
            field=models.TextField(max_length='30'),
        ),
    ]
