# Generated by Django 2.1.7 on 2021-03-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210305_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imie',
            field=models.TextField(default=' ', max_length='30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nazwisko',
            field=models.TextField(default=' ', max_length='30'),
            preserve_default=False,
        ),
    ]
