# Generated by Django 2.0.5 on 2021-03-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210305_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='miejscowosc',
            field=models.TextField(default=' ', max_length='30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='opis',
            field=models.TextField(max_length='500'),
        ),
    ]
