# Generated by Django 2.2.4 on 2021-03-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_displayusername_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='profile',
            name='affinity',
            field=models.BooleanField(choices=[(True, 'Nauczyciel'), (False, 'Uczen')], default=True),
            preserve_default=False,
        ),
    ]
