# Generated by Django 2.2.19 on 2021-03-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210315_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affinity',
            field=models.BooleanField(),
        ),
    ]
