# Generated by Django 2.2.19 on 2021-03-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210319_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affinity',
            field=models.BooleanField(choices=[(True, 'Nauczyciel'), (False, 'Uczen')]),
        ),
    ]
