# Generated by Django 2.2.19 on 2021-03-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210319_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='affinity',
        ),
    ]
