# Generated by Django 2.2.19 on 2021-03-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_profile_affinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nauczyciel',
            field=models.BooleanField(default=False),
        ),
    ]
