# Generated by Django 2.2.19 on 2021-03-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_profile_nauczyciel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nauczyciel',
        ),
        migrations.AddField(
            model_name='profile',
            name='u',
            field=models.CharField(choices=[('0', 'LinkedInUser'), ('1', 'FacebookUser')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
