# Generated by Django 2.2.19 on 2021-03-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210319_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='u',
        ),
    ]
