# Generated by Django 2.2.19 on 2021-03-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_profile_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affinity',
            field=models.BooleanField(choices=[(True, 'Nauczyciel'), (False, 'Uczen')], default=1),
            preserve_default=False,
        ),
    ]
