# Generated by Django 2.2.19 on 2021-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_profile_affinity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='affinity',
        ),
        migrations.AddField(
            model_name='profile',
            name='nauczyciel',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
