# Generated by Django 2.2.19 on 2021-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210319_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nauczyciel',
            field=models.BooleanField(default=False),
        ),
    ]
