# Generated by Django 2.2.19 on 2021-03-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210319_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='displayusername',
        ),
    ]
