# Generated by Django 2.2.19 on 2021-03-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210323_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='user_report',
        ),
    ]
