# Generated by Django 2.2.19 on 2021-03-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210323_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cena',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='miejscowosc',
            field=models.CharField(choices=[('brak', 'Brak'), ('warszawa', 'Warszawa'), ('gdynia', 'Gdynia'), ('kraków', 'Kraków'), ('poznań', 'Poznań'), ('wrocław', 'Wrocław'), ('ciechanów', 'Ciechanów')], default='brak', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='przedmiot',
            field=models.CharField(choices=[('brak', 'Brak'), ('historia', 'Historia'), ('angielski', 'Angielski'), ('informatyka', 'Informatyka'), ('matematyka', 'Matematyka'), ('polski', 'Polski')], default='brak', max_length=30),
        ),
    ]
