# Generated by Django 2.2.19 on 2021-03-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210324_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='none.jpg', upload_to='profile_pics'),
        ),
    ]
