# Generated by Django 2.2.19 on 2021-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210324_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='miejscowosc',
            field=models.CharField(choices=[('', 'Brak'), ('Warszawa', 'Warszawa'), ('Gdynia', 'Gdynia'), ('Kraków', 'Kraków'), ('Poznań', 'Poznań'), ('Wrocław', 'Wrocław'), ('Ciechanów', 'Ciechanów')], default='brak', max_length=30),
        ),
    ]
