# Generated by Django 2.2.19 on 2021-03-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210324_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='file',
        ),
    ]
