# Generated by Django 2.2.19 on 2021-03-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20210324_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='file',
            new_name='image',
        ),
    ]
