# Generated by Django 2.2.19 on 2021-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20210414_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='punkty',
            field=models.CharField(default=1000, max_length=7),
        ),
    ]
