# Generated by Django 2.2.19 on 2021-04-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20210427_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='punkty',
            field=models.CharField(default=1000, max_length=7),
        ),
    ]
