# Generated by Django 2.2.19 on 2021-04-29 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0049_auto_20210428_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkty', models.CharField(default=1000, max_length=7)),
                ('user_author2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_author2', to=settings.AUTH_USER_MODEL)),
                ('user_rated2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_reported2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
