# Generated by Django 2.2.19 on 2021-04-29 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='user_rated2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rated2', to=settings.AUTH_USER_MODEL),
        ),
    ]
