# Generated by Django 2.2.19 on 2021-04-29 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0051_auto_20210429_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='user_author2',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user_rated2',
        ),
        migrations.AddField(
            model_name='rate',
            name='user_rate_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_rate_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='user_rated',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_rated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
