# Generated by Django 2.2.19 on 2021-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20210429_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='punkty',
        ),
        migrations.AddField(
            model_name='rate',
            name='ocena',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
