# Generated by Django 2.2.19 on 2021-04-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20210429_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ranga',
            field=models.CharField(default='brak', max_length=30),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ocena',
            field=models.CharField(max_length=7),
        ),
    ]
