# Generated by Django 2.2.19 on 2021-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20210429_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zweryfikowany',
            field=models.BooleanField(default=False),
        ),
    ]
