# Generated by Django 2.2.19 on 2021-05-04 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0055_profile_zweryfikowany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wzor', models.ImageField(default='none.jpg', upload_to='profile_auth')),
                ('zdjecie', models.ImageField(default='none.jpg', upload_to='profile_auth')),
                ('user_auth_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
