# Generated by Django 2.2.19 on 2021-05-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='wzor',
            field=models.ImageField(default='gest1.png', upload_to='profile_auth'),
        ),
    ]
