# Generated by Django 2.2.19 on 2021-05-04 18:32

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20210504_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='wzor',
            field=models.ImageField(default=app.models.random_string, upload_to='profile_auth'),
        ),
    ]
