# Generated by Django 2.2.19 on 2021-05-04 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20210504_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='user_auth_author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
