# Generated by Django 2.2.19 on 2021-05-05 00:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20210505_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wzor',
            field=models.ImageField(default=app.models.Profile.random_string, upload_to='profile_auth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zdjecie',
            field=models.ImageField(default='none.jpg', upload_to='profile_auth'),
        ),
    ]
