# Generated by Django 2.2.4 on 2021-05-26 00:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20210526_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='przedmiot',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('brak', 'Brak'), ('historia', 'Historia'), ('angielski', 'Angielski'), ('informatyka', 'Informatyka'), ('matematyka', 'Matematyka'), ('polski', 'Polski')], default='brak', max_length=53),
        ),
    ]
