# Generated by Django 2.2.4 on 2021-05-28 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20210528_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commented', to=settings.AUTH_USER_MODEL),
        ),
    ]
