# Generated by Django 2.2.4 on 2021-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20210528_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_title',
            field=models.CharField(max_length=30),
        ),
    ]
