# Generated by Django 2.2.4 on 2021-05-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20210528_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
