# Generated by Django 2.2.4 on 2021-05-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20210528_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='miejscowosc',
            field=models.CharField(choices=[('brak', 'Brak'), ('Warszawa', 'Warszawa'), ('Gdynia', 'Gdynia'), ('Kraków', 'Kraków'), ('Poznań', 'Poznań'), ('Wrocław', 'Wrocław'), ('Ciechanów', 'Ciechanów')], default='brak', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='opis',
            field=models.TextField(default='  ', max_length='500'),
        ),
    ]
