# Generated by Django 2.2.4 on 2021-05-28 15:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20210528_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='przedmiot',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Brak', 'Brak'), ('Historia', 'Historia'), ('Angielski', 'Angielski'), ('Informatyka', 'Informatyka'), ('Matematyka', 'Matematyka'), ('Polski', 'Polski')], default='brak', max_length=53),
        ),
    ]
